<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * @mixin IdeHelperPicture
 */
class Picture extends Model
{
    use HasFactory;

    protected $fillable = [
        'filename'
    ];

    protected static function booted(): void
    {
        //parent::booted(); // TODO: Change the autogenerated stub
        // Cette méthode est appelée lors d'un delete d'une picture ($picture->delete())
        static::deleting(function (Picture $picture) {
            \Storage::disk('public')->delete($picture->filename);
        });
    }

    public function getImageUrl(): string {
        return \Storage::disk('public')->url($this->filename);
    }
}
